language: elixir

sudo: false

elixir: 1.9.4
otp_release: 22.0

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - deps
    - priv/plts

jobs:
  include:
    - stage: Check
      script:
        - mix compile --all-warnings --warnings-as-errors
        - mix format --check-formatted
        - mix coveralls.travis
        - mix dialyzer --format dialyxir
